project_id = "stffmybggmfgrkskiykl"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]

[functions.mercadolibre-auth]
verify_jwt = false

[functions.mercadolibre-webhook]
verify_jwt = false