// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stffmybggmfgrkskiykl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0ZmZteWJnZ21mZ3Jrc2tpeWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTEwMDYsImV4cCI6MjA3MjQ4NzAwNn0.WCYx_--7xABoz0KuBL-zEWvVrfaKDjMeOu9AZY1qwzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});